FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

#
# Add Ondrej PPA
#
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:ondrej/php -y

#
# Install Nginx and latest PHP version 8.0.3
#
RUN apt-get update		    \
    && apt-get install -y	\
    nginx			        \
    sqlite3			        \
    php8.0-fpm			    \
    php8.0-mysql			\
    php8.0-intl			    \
    php8.0-mbstring		    \
    php8.0-zip			    \
    php8.0-xml			    \
    php8.0-sqlite3

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/php.ini /etc/php/8.0/fpm/php.ini
COPY docker/default /etc/nginx/sites-available/default

WORKDIR /var/www/html

EXPOSE 80

CMD service php8.0-fpm start 	\
    && nginx -g 'daemon off;'	\
    && bash
